[project]
name = "filestore"
version = "0.1.0"
description = "Filestore MCP Server"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mcp>=1.9.4",
    "pydantic[email]>=2.11.5",
] 