name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - uses: astral-sh/setup-uv@v4  
    
    - name: Install dependencies with verbose output
      run: |
        echo "Installing with uv sync --dev..."
        uv sync --dev -v
        echo "Checking installed packages..."
        uv pip list
    
    - name: Debug - Check pytest installation
      run: |
        uv run python -c "import pytest; print('pytest version:', pytest.__version__)" || echo "pytest not found"
        uv tree --only-dev || echo "uv tree failed"
      
    - name: Run tests
      run: make test
      env:
        AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
        AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}