name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - uses: astral-sh/setup-uv@v4  
    
    - name: Install dependencies
      run: |
        uv sync
        uv pip install pytest>=7.0.0 pytest-asyncio>=0.21.0
      
    - name: Run tests
      run: make test
      env:
        AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
        AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}